#!/bin/sh
# Pin JACK to isolated CPU cores 2-3 for realtime performance
# (isolcpus=2,3 kernel parameter reserves these cores)
exec taskset -c 2,3 /usr/bin/jackd -t 2000 -R -P 95 -d alsa -d hw:0 -r 48000 -p 256 -n 2 -X seq -s
